apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  labels:
    app: order-service
data:
  KAFKA_SERVERS: kafka-0.kafka-headless.default.svc.cluster.local:9092,kafka-1.kafka-headless.default.svc.cluster.local:9092
  SPRING_DATASOURCE_URL: jdbc:postgresql://order-database:5432/postgres
  PRODUCT_SERVICE: http://product-service:8084
  PAYMENT_SERVICE: http://payment-service:8085
