apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
        version: v1
    spec:
      containers:
        - name: review-service
          image: sainturb/review-service:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: review-config
          securityContext:
            runAsUser: 1000