### Batch start process
PUT http://localhost:8082/api/batch/start
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImFkbWluQG1pdS5lZHUiLCJmdWxsbmFtZSI6ImFkbWluIGFkbWluIiwiaWQiOjIsInJvbGVzIjpbIkFETUlOIl0sInVzZXJuYW1lIjoiYWRtaW4ifQ.smvisH5PDc1TcyYBwUutfDBlg44PpEGzKDshFa0xpJmZnLljheB2yBkbfGCsRYp_BMWejOVccmPcOcKAPXQkRg

### Batch start process
PUT http://localhost:8082/api/bulk
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImFkbWluQG1pdS5lZHUiLCJmdWxsbmFtZSI6ImFkbWluIGFkbWluIiwiaWQiOjIsInJvbGVzIjpbIkFETUlOIl0sInVzZXJuYW1lIjoiYWRtaW4ifQ.smvisH5PDc1TcyYBwUutfDBlg44PpEGzKDshFa0xpJmZnLljheB2yBkbfGCsRYp_BMWejOVccmPcOcKAPXQkRg


### Get products
GET http://localhost:8082/api/search
