apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: account-service
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: account-service
              servicePort: 80